### ISSUE TITLE
How to give design compile arguments through settings file

### ISSUE THREAD

**Issue by Badhi** [suzizecat/slang-lsp-tools#16]
I'd like to know how to provide the design specific include/library directories to the server. I could find a setting on extension to give the configuration file, but don't know what the content of the file should be. Couldn't find a section on documentation.

**Comment by suzizecat** [comment]
Hi !

There is no GUI for this feature.

In order to add include directories, you may use the command `Diplomat: Open config file` (see [the documentation](https://suzizecat.github.io/diplomat-lsp/introduction/configuration.html#saving-and-loading-the-configuration) ) to directly open the configuration file in your editor. You may use VSCode formatter for JSON files in order to make it easy to read.

You should then have a section `includes` which contains two lists:
 - The `user` list contains the include paths which are added by the user (probably what you want to do)
 - The `system` list contains include paths that should be system paths.

Each element in this list is either an absolute path or a relative path (relative to your workspace root) to the directory to add to the include path.

For example, my config file on a demo project looks like this:
```json

{
    "excludedDiags": [],
    "excludedPaths": [
        "/mnt/hspeed/Linux/Projets/HDL/Hamster/rtl/io"
    ],
    "excludedPatterns": [
        ".*/phy",
        ".*/.*verif.*",
        ".*/synth",
        ".*/build"
    ],
    "includes": {
        "system": [],
        "user": [
            "/mnt/hspeed/Linux/Projets/HDL/Hamster/rtl/top/include"
        ]
    },
    "topLevel": "core_top",
    "workspaceDirs": [
        "/mnt/hspeed/Linux/Projets/HDL/Hamster"
    ]
}
``` 

You must have saved this configuration file at least once to generate it.

Once you added the relevant information in the JSON file, save it and reload it to the server.

**Comment by Badhi** [comment]
Just calling `Diplomat : Open config file` didn't work for me. I kept seeing following error when I activate the extension for the first time
```
error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '.../.config/Code/User/workspaceStorage/6f8c0a2a8aea2d00716ce9206ad38476/jfaucher.diplomat-host/diplomat-settings.json'
```
I had to first do `Diplomat: Save the workspace configuration from the server` and then open config again for it to open up

But either way managed to get it working. Thanks for the help

**Comment by suzizecat** [comment]
> Just calling `Diplomat : Open config file` didn't work for me. I kept seeing following error when I activate the extension for the first time

This is what I meant by 

> You must have saved this configuration file at least once to generate it.

Just for reference, I updated the documentation with some information about this problem: https://suzizecat.github.io/diplomat-lsp/introduction/configuration.html#adding-include-paths
